### ISSUE TITLE
请问有计划将DEPPN集成进来吗？

### ISSUE THREAD

**Issue by jc-ryan** [Spico197/DocEE#1]
很感谢作者对DocEE的贡献～，ACL2021中除了GIT之外，还有一篇DEPPN效果也还不错，并且是使用的并行解码的策略，会快不少。它的代码也是继承自Doc2EDAG，DEPPN：https://github.com/HangYang-NLP/DE-PPN
不知道作者是否有计划将其集成到目前这个toolkit～

**Comment by Spico197** [comment]
嗨~ 感谢您的建议。必须的！

不过原作者的开源版本repo中还存在一些问题，我还在和DE-PPN的作者进行积极有效的沟通，相关实验也已经在跑了。目前我把原始DE-PPN的代码fork之后自己尝试了一下（代码和结果在[这里](https://github.com/Spico197/DE-PPN)），现在还差几十个百分点，所以希望能先还原他们论文里的结果之后再集成进来，这样也能给大家带来最好的体验。另外关于速度的问题，我们会进行公平对比测试之后一起放出来。

再次感谢您对本项目的关注~ 如果您手头已经可以复现DE-PPN的结果的话欢迎在issue或邮件里交流，也欢迎大家PR~

**Comment by jc-ryan** [comment]
> 嗨~ 感谢您的建议。必须的！
> 
> 不过原作者的开源版本repo中还存在一些问题，我还在和DE-PPN的作者进行积极有效的沟通，相关实验也已经在跑了。目前我把原始DE-PPN的代码fork之后自己尝试了一下（代码和结果在[这里](https://github.com/Spico197/DE-PPN)），现在还差几十个百分点，所以希望能先还原他们论文里的结果之后再集成进来，这样也能给大家带来最好的体验。另外关于速度的问题，我们会进行公平对比测试之后一起放出来。
> 
> 再次感谢您对本项目的关注~ 如果您手头已经可以复现DE-PPN的结果的话欢迎在issue或邮件里交流，也欢迎大家PR~

👍👍👍

**Comment by Spico197** [comment]
Integrated (alpha version) in the latest version.
Please check [the original DE-PPN repo](https://github.com/HangYang-NLP/DE-PPN) for detailed reproduction information.

**Comment by xxllp** [comment]
good job  ！！
