### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by sauceplus** [Spico197/DocEE#14]
你好我是使用windows的学生，拜读您的论文后十分感兴趣，看了之前您关于api问题的回答，但是还是不知道下载模型后如何在我的项目中使用，您方便的话可以赐教一下嘛

**Comment by Spico197** [comment]
您好，感谢对本项目的关注。这个工具在使用时和系统无关，所以是不是windows都可。您可以在导入模型之后参考 #11 中提到的api函数实现来做预测。如果您有具体问题的话可以继续在issue中交流。

**Comment by lujiang001108** [comment]
您好，我在运行Python build_data.py 文件时，提示没有dee module ,这个dee怎么install ,我还是没懂您那个pip install-e
命令，这个怎么操作呀
![image](https://user-images.githubusercontent.com/61661721/158952150-63464142-fffa-4d12-9210-58e1acc68303.png)

**Comment by lujiang001108** [comment]
![image](https://user-images.githubusercontent.com/61661721/158952905-d5cbea86-809e-43d1-819c-e050a107bfe0.png)

**Comment by Spico197** [comment]
您好，这里我是把`dee`当做python的一个包来调用的，因此就像其它的包一样，必须在使用前先安装。因为没有上传至PyPI，所以需要进行本地安装。仓库代码clone下来之后，可以在仓库的主目录下（带`setup.py`文件的目录）运行 `pip install -e .` 命令安装。装好之后就不会报找不到包的错了。

> 您好，我在运行Python build_data.py 文件时，提示没有dee module ,这个dee怎么install ,我还是没懂您那个pip install-e 命令，这个怎么操作呀 ![image](https://user-images.githubusercontent.com/61661721/158952150-63464142-fffa-4d12-9210-58e1acc68303.png)

**Comment by Spico197** [comment]
您最后少了一个符号`.`

> ![image](https://user-images.githubusercontent.com/61661721/158952905-d5cbea86-809e-43d1-819c-e050a107bfe0.png)

**Comment by sauceplus** [comment]
十分感谢您迅速的回答！但是我现在的技术水平不是很高，看不懂shell命令，阅读了多次也无法知道您的意图。我现在的机器配置是win10+python3.6+pycharm，任务目标是对一段篇章级（500字左右）的txt进行抽取。在您方便时可否讲解一下模型的使用方法，即如何在我的.py中调用这个模型，知道很低级啦，但还是被您的项目所吸引，如果您不吝赐教我将不胜感激！

**Comment by Spico197** [comment]
> 十分感谢您迅速的回答！但是我现在的技术水平不是很高，看不懂shell命令，阅读了多次也无法知道您的意图。我现在的机器配置是win10+python3.6+pycharm，任务目标是对一段篇章级（500字左右）的txt进行抽取。在您方便时可否讲解一下模型的使用方法，即如何在我的.py中调用这个模型，知道很低级啦，但还是被您的项目所吸引，如果您不吝赐教我将不胜感激！

嗨，您好。我理解您可能有一些ddl的压力，不然不会这么着急。因为您的提问实在太过笼统，我实在是不知道该怎么回答。我欢迎任何具体的问题和讨论，但对这种笼统的问题确实无从下手。首先请先读一遍readme，之后请跟着我的思路一起走下具体的代码使用流程，或许可以解决一些你的困惑。

1. 关于看不懂shell命令的问题，只能靠您自己搜索和学习
2. 请确保您按照installation中的指示准备好了运行环境和本项目所开发的这个包
3. 如果是需要重新训练新的模型，请按照readme中的提示一步步来
4. 现在我假设您不需要训练，而只需要导入我提供的已训练好的模型权重。我最近的精力有限，可能后面才有时间写一个完整的预测脚本。不过我提供了这部分的接口，调用起来是很方便的，所以先不要着急。首先过一遍 run_dee_task.py 文件，speed test中有dee_task导入现有模型权重的接口示例，可以参考一下。之后过一下dee_task.py中的predict_one方法，这个函数的输入就是文本，输出就是结构化的事件实例。所以实现一个完整api的过程就三步：首先按照我在readme中提供的task dump中的配置文件初始化一个dee_task，之后导入已训练好的模型权重，再然后就可以调用predict_one方法函数得到想要的结果了

**Comment by sauceplus** [comment]
> 

再次感谢非常详细的回答 我会按您的回答进行详细学习 相信我很快就可以成功使用您的工具 祝您生活愉快！
