### ISSUE TITLE
关于“Before running any bash script, please ensure has been correctly set.bert_model”

### ISSUE THREAD

**Issue by sauceplus** [Spico197/DocEE#17]
你好老师，我按照您说的纠正了一些问题，很高兴项目现在已经可以运行了。但是还有一些小问题实在无法解决需要向您请教，下面我将陈述我的问题。
1. 您readme中“Before running any bash script, please ensure has been correctly set.bert_model”所指的bert模型是Google官方开源的中文模型吗（https://github.com/google-research/bert），？
2. 由于我的运行结果中分词存在问题（见图1），所有的role都只有一个字或者标点，所以我怀疑是bert没有导入的结果，因为我并没有修改您tump中的task_setting.json  "bert_model": "bert-base-chinese"，所以我的怀疑合理吗？
![KR{7$COF~(W()IQX8B K@A4](https://user-images.githubusercontent.com/57305819/159148045-a574e777-d975-49a5-aefb-60bf86826a3e.png)**图1**
![D}7OSJT }PHU}XP5%``@36](https://user-images.githubusercontent.com/57305819/159148071-4b4fd777-3567-4e81-8643-3f91c751f846.png)
![% 6 2C((9YH8$MHZK%O8QQQ](https://user-images.githubusercontent.com/57305819/159148086-7fd1155a-ee52-4dbc-b7f8-75058944cddc.png)

**Comment by sauceplus** [comment]
![}_$T7TU8X89MDP576U2WCT5](https://user-images.githubusercontent.com/57305819/159148221-a3c7f84b-6cb4-4034-9fa2-0be6de6a63d9.png)
我在这里修改了路径

**Comment by Spico197** [comment]
嗨，您好。事实上这里导入的并不是bert模型的权重，而是bert的词表（[这个](https://huggingface.co/bert-base-chinese/blob/main/vocab.txt)文件），从而进行tokenization。从预测的结果来看，像是没有正确导入模型权重造成的，与bert无关。请更正后再检查模型权重的导入部分。

**Comment by sauceplus** [comment]
您好老师，谢谢回复！您说的“请更正后再检查**模型权重**的导入部分”这个模型是bert还是PTPCG呢？因为我检查了很久bert没有什么问题（如图）。PTPCG的权重我按要求使用了task_setting.json中的参数，要避免上述情况是需要进行什么样的调参呢？
![CR1VMJ)07LG4 R)MFFYO0HG](https://user-images.githubusercontent.com/57305819/159150707-792be8d5-e0ad-4750-a577-2713120b7c7e.png)

**Comment by Spico197** [comment]
是指PTPCG模型的参数导入。需要更改task_setting中的bert_model。请再检查下PTPCG的模型有没有正确导入参数。

**Comment by sauceplus** [comment]
您好，我这样模仿您之前的任务进行配置的，有什么问题或者是遗漏吗？
![Uploading YF66NVWY}E2]YXK1K$54V`1.png…]()
![2B Q __679 N1SZ)RZ`H~)7](https://user-images.githubusercontent.com/57305819/159150990-2e79cb65-fe60-4048-901b-e4ac14ede705.png)
![``Y@CDGZSM`NKCZ4I_ $QZE](https://user-images.githubusercontent.com/57305819/159150992-ef58f31f-af85-4fe6-8ee5-7fa9634b73f1.png)

**Comment by sauceplus** [comment]
![YF66NVWY}E2 YXK1K$54V`1](https://user-images.githubusercontent.com/57305819/159151035-8a0e233d-0bbf-4c6a-9ff2-c1e6e70f08c2.png)
![2B Q __679 N1SZ)RZ`H~)7](https://user-images.githubusercontent.com/57305819/159151038-c76560b2-c6fe-400f-9274-1a44cb5cd57c.png)
![``Y@CDGZSM`NKCZ4I_ $QZE](https://user-images.githubusercontent.com/57305819/159151040-db7d7550-0b14-4656-ba09-1f7a4f9213bf.png)

**Comment by sauceplus** [comment]
您好，我这样模仿您之前的任务进行配置的，有什么问题或者是遗漏吗？
![YF66NVWY}E2 YXK1K$54V`1](https://user-images.githubusercontent.com/57305819/159151076-b946d549-3f2f-4722-aa97-05ac7230fbb8.png)
![2B Q __679 N1SZ)RZ`H~)7](https://user-images.githubusercontent.com/57305819/159151080-611b6eee-ef6d-44d7-be99-45f2158fd244.png)
![``Y@CDGZSM`NKCZ4I_ $QZE](https://user-images.githubusercontent.com/57305819/159151087-72bf3788-2930-4479-9f27-0f20911a2e6e.png)

**Comment by sauceplus** [comment]
![YF66NVWY}E2 YXK1K$54V`1](https://user-images.githubusercontent.com/57305819/159151116-933260a9-a28b-437e-a896-8038c9eba48f.png)

**Comment by Spico197** [comment]
是检查 PTPCG 的模型导入，不是 bert 的导入。
我已经提供了推理接口的调用方法，请检查 FAQ 的 Q4 和 `inference.py` 。

**Comment by sauceplus** [comment]
十分感谢老师在这几天内对我莫大的帮助，我将继续学习您的模型，期待能参与更深层次的讨论。祝您工作和生活愉快，如果有机会见到您会主动向您当面致谢！期待您的新进展
