### ISSUE TITLE
我运行bash scripts/run_git_dueefin_withtgg.sh命令时候，报错：读不到json格式对应的文件，然后Output文件里面生成的是pkl格式的文件。老师您在生成这个文件时候在哪里呀，，

### ISSUE THREAD

**Issue by lujiang001108** [Spico197/DocEE#19]
![image](https://user-images.githubusercontent.com/61661721/159424114-831079ee-94ea-4bf0-bc2a-8a5ace560f2f.png)
![image](https://user-images.githubusercontent.com/61661721/159424204-00355c36-dfa3-4148-a4ea-3cc3e1e767db.png)

**Comment by Spico197** [comment]
您好，会生成在您图里的这个文件夹内。可以看看详细的输出log，检查是不是中间出了什么问题或者报了什么错误。例如这里会有json文件dump的记录。
![image](https://user-images.githubusercontent.com/22840952/159426487-97132394-3c95-4a4b-8381-57102d800084.png)

**Comment by lujiang001108** [comment]
![image](https://user-images.githubusercontent.com/61661721/159606465-c58f4b38-f248-4eb2-a487-32268082c9c4.png)

![8d57adf0e57f5d0dd52aeaa7b6a2422](https://user-images.githubusercontent.com/61661721/159606374-da97567b-989f-40a9-9cea-d0fd0f1b4049.png
老师好，我昨天用您的PTPCG在DuEEfin数据集运行完结果生成luge_t1_submit_new.json文件，这个文件打开是第二幅图片的样子，这个您代码里面有继续数据后处理成百度需要的结果的代码嘛，目前生成的文件里面包含comments。麻烦老师啦

**Comment by Spico197** [comment]
可以在这里找到后处理脚本：[dueefin_post_process.py](https://github.com/Spico197/DocEE/blob/main/dueefin_post_process.py)，把 `to_remove_filepath` 和 `save_filepath` 改下即可。

**Comment by lujiang001108** [comment]
谢谢老师。现在有一个问题就是：我运行GIT和DOC2EDG模型时候，两个都是提示FileNotFoundError: [Errno 2] No such file or directory: 'Exps/Doc2EDAG_DuEE_fin_with_trigger/Output/dee_eval.dev.pred_span.Doc2EDAG.1.json'，找不到这个json文件的错误，但是运行PTPCG就会生成对应的Json文件，我还是不会改这么错，老师可以帮我抽空看看嘛，谢谢老师回复我上个问题，那个解决啦
![image](https://user-images.githubusercontent.com/61661721/159717406-b8eac348-aee2-4229-9514-5ee4f5059538.png)

![image](https://user-images.githubusercontent.com/61661721/159717265-648d631b-acf3-43d4-92c4-ce48a800ff02.png)

**Comment by Spico197** [comment]
上图中是推理时没有找到文件。确认模型经过训练了吗？可以把训练时的日志发一下。PTPCG和Doc2EDAG、GIT使用的是同一个DEETask，不会出现一个模型有评价的json文件，另一个没有的情况。

**Comment by lujiang001108** [comment]
![image](https://user-images.githubusercontent.com/61661721/159835110-d904c1f3-05de-4cbc-97c8-89c352a91505.png)

[Doc2EADG.log](https://github.com/Spico197/DocEE/files/8338141/Doc2EADG.log)
[GIT.log](https://github.com/Spico197/DocEE/files/8338142/GIT.log)
[PTPCG.log](https://github.com/Spico197/DocEE/files/8338143/PTPCG.log)

**Comment by lujiang001108** [comment]
老师好，这是三个模型的日志。PTPCG是没有问题的，然后另外两个都只生成了pkl ，没有生成json。我是用的包含触发词信息的模型

**Comment by Spico197** [comment]
没在日志中看到任何的报错信息。如果您是使用nohup启动脚本的话，麻烦放下nohup启动的版本。在Doc2EDAG和GIT的日志中均未看到完整的训练过程，不确定是不是异常中断了。另外在日志中是能看到有json文件输出的，如果确定没有的话应该是会报错的，但现在这个版本的日志输出中看不到错误提示。

![image](https://user-images.githubusercontent.com/22840952/159853558-08096808-fde9-4390-ac83-f3385cd6511b.png)

![image](https://user-images.githubusercontent.com/22840952/159853358-3fb80a5c-89c6-4398-9d8b-bf29d0587d99.png)

**Comment by lujiang001108** [comment]
老师好，这是nohup.out文件
Traceback (most recent call last):
  File "run_dee_task.py", line 15, in <module>
Traceback (most recent call last):
  File "run_dee_task.py", line 15, in <module>
    from dee.tasks import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/__init__.py", line 1, in <module>
    from .dee_task import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/dee_task.py", line 12, in <module>
    from dee.tasks import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/__init__.py", line 1, in <module>
    from transformers.models.bert.modeling_bert import BertConfig
ModuleNotFoundError: No module named 'transformers.models'
    from .dee_task import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/dee_task.py", line 12, in <module>
    from transformers.models.bert.modeling_bert import BertConfig
ModuleNotFoundError: No module named 'transformers.models'
Traceback (most recent call last):
  File "run_dee_task.py", line 15, in <module>
    from dee.tasks import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/__init__.py", line 1, in <module>
    from .dee_task import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/dee_task.py", line 12, in <module>
    from transformers.models.bert.modeling_bert import BertConfig
ModuleNotFoundError: No module named 'transformers.models'
Traceback (most recent call last):
  File "run_dee_task.py", line 15, in <module>
    from dee.tasks import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/__init__.py", line 1, in <module>
    from .dee_task import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/dee_task.py", line 12, in <module>
    from transformers.models.bert.modeling_bert import BertConfig
ModuleNotFoundError: No module named 'transformers.models'
Traceback (most recent call last):
  File "/data/anaconda3/envs/py37env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/anaconda3/envs/py37env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/anaconda3/envs/py37env/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/data/anaconda3/envs/py37env/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/data/anaconda3/envs/py37env/bin/python', '-u', 'run_dee_task.py', '--local_rank=3', '--task_name', 'Doc2EDAG_DuEE_fin_with_trigger', '--data_dir=Data/DuEEData', '--bert_model=bert-base-chinese', '--model_type=Doc2EDAG', '--cpt_file_name=Doc2EDAG', '--gradient_accumulation_steps=16', '--train_batch_size=64', '--eval_batch_size=2', '--resume_latest_cpt=False', '--num_train_epochs=100', '--run_mode=luge_with_trigger', '--event_type_template=luge_with_trigger', '--skip_train=False', '--load_dev=True', '--load_test=True', '--load_inference=False', '--inference_epoch=-1', '--run_inference=False', '--inference_dump_filepath=doc2edag_duee_fin_with_trigger.json', '--skip_train=False', '--parallel_decorate']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "run_dee_task.py", line 15, in <module>
    from dee.tasks import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/__init__.py", line 1, in <module>
    from .dee_task import DEETask, DEETaskSetting
  File "/data/newspace/jiang/DoCEE/dee/tasks/dee_task.py", line 12, in <module>
    from transformers.models.bert.modeling_bert import BertConfig
ModuleNotFoundError: No module named 'transformers.models'

**Comment by lujiang001108** [comment]
[nohup.log](https://github.com/Spico197/DocEE/files/8339158/nohup.log)

**Comment by lujiang001108** [comment]
![image](https://user-images.githubusercontent.com/61661721/159861609-bb189cf6-8a3c-46de-b0d4-94715a296ea9.png)
这个也能正常显示

**Comment by Spico197** [comment]
nohup里报错的问题是没有安装最新版本的transformers库，可以`pip install -U transformers`升级一下。

**Comment by lujiang001108** [comment]
![image](https://user-images.githubusercontent.com/61661721/160073395-49abaf9e-0f99-48a2-a5bf-2b4e049bae24.png)
![image](https://user-images.githubusercontent.com/61661721/160073430-13c0ff7e-e422-4c6f-bbff-2ac17b5ce4f7.png)
老师好，我重新安装了transformers库，GIT和Doc2EDAG两个模型都无法训练，无法生成对应的json格式文件，老师方便帮我看看嘛，我把我邮箱发给老师。lujiangsxu@163.com

**Comment by lujiang001108** [comment]
我的运行命令是：bash scripts/run_doc2edag_dueefin_withtgg.sh
这是两个日志
[Uploading log.log…]()
[nohup.log](https://github.com/Spico197/DocEE/files/8348336/nohup.log)

**Comment by Spico197** [comment]
图中的错误不全，前面的错误信息没有显示，后面的这些提示无法定位问题。
您的这两个log第一个链接是个页面，应该是没上传，第二个log显示的还是transformers库版本的问题。
我又在本地做了下测试，按当前版本代码训练确实没什么问题，请检查下您的环境，根据错误提示定位具体的问题。训练时可以先把inference部分的shell命令注释掉。

![image](https://user-images.githubusercontent.com/22840952/160085784-0d2b1979-3c40-42c4-a9a4-ef2c72a4ed1d.png)

**Comment by lujiang001108** [comment]
老师好，我似乎找到了问题所在，之前没有Json格式文件是因为我注释掉了dee_task.py中的这两个函数，所有无法生成对应的Json格式文件。然后您的helper文件夹下的dee.py脚本中，没有下方红色箭头的这两个函数，可以给我单独发一份包含这两个函数的脚本嘛。
还有一个问题想请教老师。bert路径您之前是您的路径，这个需要我改成自己的吗？您的模型中用到bert预训练了吗？
感谢老师答疑，万分感谢您!
















在 2022-03-25 16:44:03，"Tong Zhu（朱桐）" ***@***.***> 写道：

图中的错误不全，前面的错误信息没有显示，后面的这些提示无法定位问题。
您的这两个log第一个链接是个页面，应该是没上传，第二个log显示的还是transformers库版本的问题。
我又在本地做了下测试，按当前版本代码训练确实没什么问题，请检查下您的环境，根据错误提示定位具体的问题。训练时可以先把inference部分的shell命令注释掉。

**Comment by Spico197** [comment]
- 看不到您发的图片，似乎没有正常发送。
- bert的路径需要改成您本地的bert目录。模型中没有用到bert预训练，只是用了bert的tokenizer，所以只要保证您bert目录下有`vocab.txt`文件即可。当然我们也提供了使用bert作为预训练模型微调的方案，需要您浏览下源码，对参数设置做些调整。

**Comment by lujiang001108** [comment]
老师好，我似乎找到了问题所在，之前没有Json格式文件是因为我注释掉了dee_task.py中的这两个函数，所有无法生成对应的Json格式文件。然后您的helper文件夹下的dee.py脚本中，没有下方红色箭头的这两个函数，可以给我单独发一份包含这两个函数的脚本嘛。
还有一个问题想请教老师。bert路径您之前是您的路径，这个需要我改成自己的吗？您的模型中用到bert预训练了吗？
感谢老师答疑，万分感谢您!
















在 2022-03-25 16:44:03，"Tong Zhu（朱桐）" ***@***.***> 写道：

图中的错误不全，前面的错误信息没有显示，后面的这些提示无法定位问题。
您的这两个log第一个链接是个页面，应该是没上传，第二个log显示的还是transformers库版本的问题。
我又在本地做了下测试，按当前版本代码训练确实没什么问题，请检查下您的环境，根据错误提示定位具体的问题。训练时可以先把inference部分的shell命令注释掉。

**Comment by Spico197** [comment]
您把相同的内容发了两遍，但还是没有收到图片👀

**Comment by lujiang001108** [comment]
老师好，我似乎找到了问题所在，之前没有Json格式文件是因为我注释掉了dee_task.py中的这两个函数，所有无法生成对应的Json格式文件。然后您的helper文件夹下的dee.py脚本中，没有下方红色箭头的这两个函数，可以给我单独发一份包含这两个函数的脚本嘛。
还有一个问题想请教老师。bert路径您之前是您的路径，这个需要我改成自己的吗？您的模型中用到bert预训练了吗？
感谢老师答疑，万分感谢您!
![image](https://user-images.githubusercontent.com/61661721/160279750-83287af5-0e76-43da-87c7-52864905f985.png)
![image](https://user-images.githubusercontent.com/61661721/160279761-807202fb-b9f2-4dd5-a857-ef6745c8ea13.png)

**Comment by Spico197** [comment]
图片已收悉。您本地的代码版本似乎落后于当前repo的main分支。这两个类您直接注释掉即可，建议更新至最新版的代码。关于bert路径的问题请见上面的回复。

**Comment by lujiang001108** [comment]
老师好，我更新了最新的代码，现在只有GIT运行时，没有生成对应的./Exps/GIT_DuEE_fin/GITModel.task_setting.json'文件。
![image](https://user-images.githubusercontent.com/61661721/160415036-f82a53bc-7d2e-4ef1-b60d-b380e8a4f58a.png)

**Comment by Spico197** [comment]
您截的图完全无法定位问题所在，我也无法复现您的错误。请仔细检查训练过程中的日志和输出的信息。不论是PTPCG、Doc2EDAG还是GIT，都是在 `run_dee_task.py` 的第272行保存task_setting文件，除非根本就没有开始训练。

https://github.com/Spico197/DocEE/blob/1fd933f817f7c48b778fa6f2d0c4fa8a2648f58d/run_dee_task.py#L272
