### ISSUE TITLE
EE with triggers 

### ISSUE THREAD

**Issue by igorhuangchao** [Spico197/DocEE#2]
do you have any materials or repo work for the doc EE with triggers ? thanks.

**Comment by Spico197** [comment]
Hi. Currently, this repo works well on Doc-EE **with** triggers. You can take triggers as arguments and build DAG chains, or follow what we've done in PTPCG on DuEE-fin.

As to other repos for Doc-EE tasks with triggers (especially datasets in English), you can refer to [this preprint paper](https://openreview.net/forum?id=og2PWB6U0K0) to locate suitable datasets first, and check the collections below to find relevant papers or repos.
- [BaptisteBlouin/EventExtractionPapers](https://github.com/BaptisteBlouin/EventExtractionPapers)
- [carrie0307/DL_EventExtractionPapers](https://github.com/carrie0307/DL_EventExtractionPapers)
- [ll0ruc/event-extraction-paper](https://github.com/ll0ruc/event-extraction-paper)

![image](https://user-images.githubusercontent.com/22840952/146303567-4b3e9671-1817-4406-b047-00b0f19b0bdb.png)
