### ISSUE TITLE
老师您好  有一些使用的方法请教

### ISSUE THREAD

**Issue by setsaill** [Spico197/DocEE#20]
我按照您说的哪个方法解决dee导入问题，可是还是出现了下面的错误，不知道是不是哪里有问
![屏幕截图 2022-03-29 230348](https://user-images.githubusercontent.com/39605402/160645868-7ca23890-3a8f-481b-b759-069895fd3561.png)
题

然后还要请教您下那个dump-task是怎么使用的，我是npl小白，还有很多问题想不通，望您帮忙解惑

**Comment by setsaill** [comment]
我早上用git clone了这个项目 可还是出现了问题 您帮我看下可能是啥问
![屏幕截图 2022-03-30 073240](https://user-images.githubusercontent.com/39605402/160723195-6606d325-c8f2-46ef-8e61-c42a44068f28.png)
![1](https://user-images.githubusercontent.com/39605402/160723211-425f3b5d-c613-4ed0-876c-3a287a9d0317.png)
题

**Comment by Spico197** [comment]
错误提示应该还是比较明确的。请先确保您已经安装了README Installation 一节中提到的依赖库。

**Comment by Spico197** [comment]
> 我早上用git clone了这个项目 可还是出现了问题 您帮我看下可能是啥问题

这个问题应该是windows特有的编码问题，建议直接把出问题的源码部分注释掉

**Comment by setsaill** [comment]
谢谢您这么及时的回复我 
![屏幕截图 2022-03-30 105308](https://user-images.githubusercontent.com/39605402/160741790-18c50b03-714e-4513-b6df-4ba2a3e8bb79.png)
如果我把这个注释掉下面 long_discription会报错  请问这个重要吗

**Comment by Spico197** [comment]
不重要，可以直接注释。
本issue已被关闭，如果有新问题请开新的issue，否则可能会收不到提示消息。
