### ISSUE TITLE
您好 关于GIT的GCN输出那一段如何理解

### ISSUE THREAD

**Issue by catcatcatll** [Spico197/DocEE#21]
您好老师， 我在看这几个模型的时候，有一些疑问，请问GIT在做ner的时候，是使用的几层Transformer呢？
构成异构图的时候，GCN是输出的是什么呢？包括后续事件检测时，使用的是什么来代表文档向量进行事件分类的呢？
看论文和代码的时候有些没看懂，希望得到老师您的解答。
谢谢🙏

**Comment by Spico197** [comment]
GIT的相关内容最好还是去GIT原始repo中提问。这里只说我的个人理解。
- 从论文中给出的参数来看，GIT的NER部分使用的是8层transformer encoder；
- GCN输出的是融合其它mention和sentence之后的mention表示；
- 事件检测部分和Doc2EDAG相同，都是把句子表示pooling之后，得到文档的表示，再分别用每个事件类型单独的分类器做事件分类。整个过程是一个多标签分类。

**Comment by catcatcatll** [comment]
嗯嗯 谢谢老师。
