### ISSUE TITLE
有关于一些使用上的问题

### ISSUE THREAD

**Issue by setsaill** [Spico197/DocEE#23]
谢谢您之前对我的指导，现在问题解决了，我翻看了您之前对其它一些同学解答的问题，可谓是比较详细的解答的，但是其中对于刚入门的我还是有点使用上的问题想向您请教，第一个图是您回答的一个issue,我不太理解”使用task dump中配置文件初始化一个dee_task，之后导入已训练好的模型权重“这句话（使用上的流程），期待您的回复
![屏幕截图 2022-03-30 114442](https://user-images.githubusercontent.com/39605402/160747603-b3223776-887f-4310-869b-40804653cfc3.png)
![屏幕截图 2022-03-30 114829](https://user-images.githubusercontent.com/39605402/160747667-a5a9e772-534f-457b-a6cd-cc3f8c353974.png)

**Comment by Spico197** [comment]
请查看 inference.py 文件。另外工具使用类issue请务必按照template进行提问。
