### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by setsaill** [Spico197/DocEE#24]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [ ] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [ ] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [ ] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [ ] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem

My problem is ...
老师你好，我是这几天才正式用github的，您说的严格按照模板我不知道是不是指我这个，如果有问题，还望您海涵。
我这里还有几个问题请教您（还要这么麻烦您我还真有点不好意思了~）
1.inteference.py里的bert-base-chinese是不是图一里的那个，这里面还有哪些文件是必须要的呀（vocab.txt当然是需要的）
2.图二里您说的过一遍是指执行一遍程序吗，因为我执行了interference.py出现了图三的结果，我不知道是哪里导致出现这种问题，所以才问您这个简单的问题的~
3.如果是运行的话您能大致说下执行流程吗，我看您readmd看的有点迷糊，我这里是想用您的模型执行一些预测

![屏幕截图 2022-03-30 132719](https://user-images.githubusercontent.com/39605402/160759056-bd9753ef-5730-4fd7-9f1a-31560365df0e.png)
![屏幕截图 2022-03-30 114442](https://user-images.githubusercontent.com/39605402/160759108-95e6af0e-2479-4038-ab60-3b94239d2c09.png)
![屏幕截图 2022-03-30 134430](https://user-images.githubusercontent.com/39605402/160760012-4343efc7-96b0-4537-933f-4f2fdcc53023.png)

You can reproduce the problem by ...

I have tried ..., but it goes to ...

I have checked the source codes, and the problem may come from ...

## Environment

| Environment               | Values        |
| :------------------------ | :------------ |
| System                    | Windows/Linux |
| GPU Device                |               |
| CUDA Version              |               |
| Python Version            |               |
| PyTorch Version           |               |
| dee (the Toolkit) Version |               |

## Full Log

```
Log:

```

**Comment by Spico197** [comment]
您好，按照错误提示的信息，程序没有找到您的任务文件夹。`bert-base-chinese` 是图一里的。平时如果使用 bert，我们会下载 `pytorch_model.bin`, `vocab.txt` 和 `config.json` 文件，这里都下载也可以，只下载后两个（`vocab.txt` 和 `config.json`）也可以
1. 请先将README中的 task dump 下载至本地并解压
2. 修改 `inference.py` 中的 `task_dir` 至您本地的任务文件夹
3. 修改 `inference.py` 中的 `bert_model_dir` 至您本地可用的 bert 文件夹

**Comment by setsaill** [comment]
好的好的  问题解决了 非常感谢您一上午对我的耐心答复 祝您工作顺利心想事成~    谢谢~
