### ISSUE TITLE
关于标签的统计

### ISSUE THREAD

**Issue by sauceplus** [Spico197/DocEE#25]
** Idea sharing **
两个事件之间在剪枝后，可能之前还存在关系，是否可以挖掘出之前两个事件的关系。因为两个事件团不是互斥的关系。

** Problems **
有没有关于role和eventType的所有标签模板呢（也就是图中的name和fields里的标签）？我想看一下分类个数，以及能不能拓展。

** Others **
无
![($749ZG8 N(FCPU{U Z@@$N](https://user-images.githubusercontent.com/57305819/161277600-089ab25b-a28f-4e69-adfc-f58f8b6805fb.png)

**Comment by Spico197** [comment]
1. 很不错的想法。也有一些工作在利用事件间关系增强事件抽取效果，可以检索一下。PTPCG或许可以利用共享要素来建模多实例间的事件抽取，但为了保持模型的简易性，我们没有额外增加建模关系的图神经网络
2. 可以写脚本统计下 `dee/event_types/zheng2019_trigger_graph.py` 中的 `event_type_fields_list` 中的 type 和 fields

**Comment by sauceplus** [comment]
感谢您的回答！
