### ISSUE TITLE
关于事件类型

### ISSUE THREAD

**Issue by sauceplus** [Spico197/DocEE#26]
** Problems **
又来打扰您啦，感谢您之前给我的对于标签统计的方法，我已经完成了对__dee/event_types/zheng2019_trigger_graph.py__中标签的统计。但还有一些问题，针对您所提供的 **duee-fin 事件类型及对应角色.pdf** 中一共有13中事件类型的分类，而在我的统计中只有五种（如图）。请问您是否实现了涵盖所有事件分类的方法？或者说这是您留给读者自己拓展的地方吗？
![(1U{5OB% 3{)(V IBCVQL1S](https://user-images.githubusercontent.com/57305819/161764196-3911327c-df90-4fc3-bdd1-3eb555d98b2d.png)

**Comment by Spico197** [comment]
DuEE-fin数据集的 template 在：
- `dee/event_types/luge_with_trigger.py`
- `dee/event_types/luge_without_trigger.py`

**Comment by sauceplus** [comment]
好嘞，请问这13种分类在[inference.py](https://github.com/Spico197/DocEE/blob/main/inference.py)中实现了嘛？

**Comment by Spico197** [comment]
template 和推理无关，DuEE-fin数据集上的模型需要自己训练后参考 [inference.py](https://github.com/Spico197/DocEE/blob/main/inference.py) 文件内的调用方法做些配置上的改动。

**Comment by sauceplus** [comment]
谢谢指点！
