### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by setsaill** [Spico197/DocEE#27]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [ ] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [ ] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [ ] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [ ]  I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem

My problem is ...

You can reproduce the problem by ...

![屏幕截图 2022-04-10 155050](https://user-images.githubusercontent.com/39605402/162608416-f8a3eb77-82bf-4530-8dd8-c1e28435fa64.png)
![屏幕截图 2022-04-10 155024](https://user-images.githubusercontent.com/39605402/162608413-cd165356-5550-462f-9352-8b5ac8f99ef4.png)
老师，我运行程序发现有些实体属性识别不出来（比如公司名识别出来了，但是法院裁定时间识别不出来，而且试了很多文本都出现这种问题），请问这可能是什么问题呢？上面我附带了输出的一些我认为有可能的问题，期待您的解答~

I have tried ..., but it goes to ...

I have checked the source codes, and the problem may come from ...

## Environment

| Environment               | Values        |
| :------------------------ | :------------ |
| System                    | Windows/Linux |
| GPU Device                |               |
| CUDA Version              |               |
| Python Version            |               |
| PyTorch Version           |               |
| dee (the Toolkit) Version |               |

## Full Log

```
Log:

```

**Comment by setsaill** [comment]
![屏幕截图 2022-04-10 155641](https://user-images.githubusercontent.com/39605402/162608483-40893400-7850-46b8-abc0-0b4792127c95.png)
就出现这种问题，大量的othertype

**Comment by Spico197** [comment]
模型已经做了它能做的

**Comment by setsaill** [comment]
好的好的  叨扰啦~
