### ISSUE TITLE
想问问大佬投了什么顶会

### ISSUE THREAD

**Issue by wuhua5027** [Spico197/DocEE#30]
** Idea sharing **
While sharing what you want to do, make sure to protect your ideas.

** Problems **
If you have any questions about event extraction, make sure you have read the latest papers or searched on the Internet.

** Others **
Other things you may want to share or discuss.
****

**Comment by Spico197** [comment]
嗨，您好。目前论文已被 IJCAI'22 录用。我们会在今年 AIS 论文预讲会 5月15日上午10:50-12:10 的 Information Extraction and Retrieval session 中介绍我们的工作。欢迎来玩~

AIS预讲会地址：https://mp.weixin.qq.com/s/QNNahSvsluKpd2hzKElhgw

**Comment by wuhua5027** [comment]
哇！祝贺！终于等到您的好消息！一定按时参加~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Spico197/DocEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Spico197/DocEE] 想问问大佬投了什么顶会 (Issue #30)





 
嗨，您好。目前论文已被 IJCAI'22 录用。我们会在今年 AIS 论文预讲会 5月15日上午10:50-12:10 的 Information Extraction and Retrieval session 中介绍我们的工作。欢迎来玩~
 
AIS预讲会地址：https://mp.weixin.qq.com/s/QNNahSvsluKpd2hzKElhgw

**Comment by Spico197** [comment]
感谢捧场，因为主办方只给5分钟的介绍时间，所以可能不会讲太多细节。您可以在[这里](https://spico197.github.io/files/talks/84-%E6%9C%B1%E6%A1%90-AIS2022-PTPCG.pdf)查看本次汇报的PPT，欢迎继续邮件和issue区交流。

**Comment by wuhua5027** [comment]
好的！感谢！再次祝贺！加油~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Spico197/DocEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Spico197/DocEE] 想问问大佬投了什么顶会 (Issue #30)





 
感谢捧场，因为主办方只给5分钟的介绍时间，所以可能不会讲太多细节。您可以在这里查看本次汇报的PPT，欢迎继续邮件和issue区交流。
