### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by sauceplus** [Spico197/DocEE#31]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [x] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [x] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [x] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [x] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem

老师你好，我现在想重新训练ptpcg模型，运行run_ptpcg.sh发现我的电脑配置太低，所以准备申请云平台进行加速。我阅读了dee_task.py，现在我是否通过shell运行run_dee_task.py，就可以获得我想要的模型在Exps文件中？（不知道为啥，dee_task.train(save_cpt_flag=in_argv.save_cpt_flag)中的save_cpt_flag=False，意思是不保存模型吗？）

**Comment by Spico197** [comment]
您好，`save_cpt_flag=False` 是指每轮评价前不保存模型权重。不过 `run_ptpcg.sh` 中设置了 `save_best_cpt=True`，即 评价结束之后若当前轮次的模型结果大于历史最佳值时会保存最佳模型。这样可以降低硬盘空间的占用。不过您也可以把 `save_cpt_flag` 设置为`True`，从而每轮都保存一个模型权重。都可以。

**Comment by sauceplus** [comment]
![QQ截图20220428210940](https://user-images.githubusercontent.com/57305819/165759605-e95cd74b-f360-4a3d-8958-6c50eff51ef7.png)
太巧妙了老师！如图，是不是到“if in_argv.run_inference:”，模型就已经完成训练并输出了呢？“run_inference”这一个if的操作意义是什么呢？

**Comment by Spico197** [comment]
1. 是的，到 `run_inference` 之前如果没有 `skip_train` 的话模型就已经训练完毕了；
2. `run_inference` 是为了打比赛做的接口，会读取`inference_file_name`文件，并在`inference_dump_filepath`中生成输出结果，具体可以看下相关代码。如果是在千言DuEE-fin数据集上做的实验，那么需要生成结果文件，经过`dueefin_post_process.py`处理后提交至系统进行线上评测。

**Comment by sauceplus** [comment]
原来是这样老师，看了半天inference_dump_filepath这个我以为老师又加入了什么测试方法呢hh
![{MF7O)V{{4O2C WZGR3JZKV](https://user-images.githubusercontent.com/57305819/165761921-479996b2-1654-43c5-90f2-1d859dcf52f8.png)
那既然这样，我的目的只是为了训练模型并输出，剩下我刷蓝的5个if我都可以去掉吧？

**Comment by Spico197** [comment]
图中320行及之后的内容要保留，是输出最终评价结果用的。其它选中部分可以删除或按argparse中的相关设定设置。如果您使用的是`run_ptpcg.sh`文件运行，那么这些保留也没关系，不会被调用。

**Comment by sauceplus** [comment]
好滴老师。云平台无法使用shell，我准备将您shell中的参数转移到python脚本中。最后向您确认一下，我只要按run_ptpcg.sh文件的步骤进行训练，就可以用于预测的模型吧？（因为云平台要按小时付费，害怕训练费了。。）

**Comment by Spico197** [comment]
是的。如果不放心的话您可以从`train.json`里抽48个文档，命名为`sample_train_48.json`，然后用`stat.py`处理一下，生成`typed_sample_train_48.json`文件。或者直接从`typed_train.json`文件中抽一些实例，把名字改成`typed_sample_train_48.json`。
在确保`Data`目录中有`typed_sample_train_48.json`文件之后，把`num_train_epochs`设置成1，`run_mode`设置为`"debug"`，然后运行一下看看能不能正常跑通。
这个测试只需要跑几分钟。

**Comment by sauceplus** [comment]
![{76NF)$I2RU 1{38VG38MJG](https://user-images.githubusercontent.com/57305819/165768383-b9d67cea-d398-4568-a0f0-00d7c40c48ec.png)
老师您在这已经编写了debug的48个样例，我是否可以直接使用？

**Comment by Spico197** [comment]
可以的

**Comment by sauceplus** [comment]
![HYVMJQ2MP}HLPLOERB4@IIW](https://user-images.githubusercontent.com/57305819/165770203-608e0b9e-38f3-4949-a14d-10884bf0804b.png)
芜湖！感谢老师！！

**Comment by sauceplus** [comment]
老师再打扰一下，有如下问题：
![C6MHDT 7P`_ GN`4HT@ 40](https://user-images.githubusercontent.com/57305819/165881406-806d454c-545a-4c5d-a5a7-2064431a5b36.png)
![RNWB25G${M4R J$)A(P@I2H](https://user-images.githubusercontent.com/57305819/165881411-7dfc2646-b043-436a-93c5-c0d7023cef95.png)

1.上图中从e1-e4，模型的loss从414降至1.82，请问loss是否可以正确反映模型的精度？
2.Docee项目中，所有包含“inference”的元素，是不是都是老师用于参与比赛的，与模型训练无关？
![HO6DV1{0`N6YQ873CH1{~@N](https://user-images.githubusercontent.com/57305819/165881713-070292d8-7d1f-4234-b6fb-5d48f45a868d.png)
