### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Sniper-LZX** [Spico197/DocEE#32]
老师，您好。初入事件抽取这一领域，或许是处于零基础阶段。
有些文件看不懂具体实现什么样的功能：
![1652349711(1)](https://user-images.githubusercontent.com/42790059/168045975-d0294d71-f52f-4527-9f0f-d7e456d581ee.png)
可以麻烦老师给予一些解答吗

**Comment by Spico197** [comment]
您好，感谢对本项目的关注。抱歉现在项目文档还不太完善。
关于Data文件夹里的代码，可以先看下README。README里没有解释的部分都是一些数据分析类的代码，统计数据特点的，一般用不上，就当它们不存在就行。
其他部分的代码可以按照README中提到的训练和推理的过程，从入口出发，打断点慢慢理解。

**Comment by Sniper-LZX** [comment]
还有疑问就是To Reproduce Results in Paper中的bert_model设置这个没理解该如何设置？感谢老师回答。

**Comment by Spico197** [comment]
比如PTPCG在ChFinAnn数据集下的训练脚本：[--bert_model='bert-base-chinese'](https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/scripts/run_ptpcg.sh#L27)，如果你本地有`bert-base-chinese`的缓存的话，可以直接把这里改成你的缓存文件夹。

**Comment by Sniper-LZX** [comment]
好的老师，我也确实有太多不懂的初级知识了，目前也确实很难提问出具体的问题，感谢您的回答

**Comment by Spico197** [comment]
不客气，有问题欢迎在issue区继续交流~
