### ISSUE TITLE
为什么`ner_token_labels` 里面没有包含扩充的OtherType的实体？

### ISSUE THREAD

**Issue by chenxshuo** [Spico197/DocEE#33]
** Problems **
请问为什么在NER模型训练部分输入进模型的`ner_token_labels` 里面没有论文中提到扩充的Money, Time等实体？

我发现在[这里](https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/helper/ner.py#L230)会对entity label 进行in的判断，判断基于的dict来自于 [DEEExample](https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/helper/dee.py#L204)。 但是这个list里面没有`B-OtherType` 和 `I-OtherType`.

**Comment by Spico197** [comment]
Hi，感谢对本项目的关注。
论文中提到的 `OtherType` 包括两类：
1. 原始 ChFinAnn 数据中已经包括的 `OtherType` （前提是要使用`common_fields`中包含`OtherType`的template）：

https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/event_types/zheng2019_trigger_graph.py#L430

2. 使用正则匹配的（设置`include_complementary_ents=True`，在数据处理时hack）：

https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/helper/dee.py#L48-L67

**Comment by chenxshuo** [comment]
谢谢回复! 数据处理里面的确向`DEEExample`加入了OtherType。 但是我发现在`NERFeature` 对象里面，缺少应当扩充的实体，就导致在用`ner_token_lables`训练NER部分的时候，`ner_token_lables`没有扩充的实体，也就没起到enhancement的作用？（针对的是DocEE-Fin）。我个人觉得是否应该在 [此处](https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/helper/dee.py#L204) 添加如下两行代码？
```
entity_label_list.append("B-OtherType")
entity_label_list.append("I-OtherType")
```

**Comment by Spico197** [comment]
是的您说的没错，看来是个bug。不过我建议在下面两个模板的`common_fields`中按需添加或删除`OtherType`即可，否则一旦硬编码至repo中，会不方便后续其他人做ablation study。我会更新一下新的template。

https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/event_types/luge_with_trigger.py#L762
https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/dee/event_types/luge_without_trigger.py#L649

**Comment by chenxshuo** [comment]
的确~ 直接硬编码时如果不扩充的话就会有问题，感谢回复~

**Comment by Spico197** [comment]
感谢您对本项目的贡献

**Comment by Spico197** [comment]
Fixed in the latest version.
