### ISSUE TITLE
关于mention type和argument role

### ISSUE THREAD

**Issue by zlh-source** [Spico197/DocEE#34]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [x] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [x] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [x] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [x] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem
您好，您论文Figure 1中涉及到了两个概念：mention type和argument role，并且在Entity Representation部分也使用到了mention type这一信息。这两者的含义和区别我明白，但是在duee数据集中有mention type这个标注信息吗？我检查了一下，似乎只有argument role。

## Environment

| Environment               | Values        |
| :------------------------ | :------------ |
| System                    | Windows/Linux |
| GPU Device                |               |
| CUDA Version              |               |
| Python Version            |               |
| PyTorch Version           |               |
| dee (the Toolkit) Version |               |

## Full Log

```
Log:

```

**Comment by Spico197** [comment]
嗨您好，感谢对本项目的关注。没有mention type时，一般采用argument role作为实体的类别。这里我们也是这么处理DuEE-fin的，具体代码如下：

https://github.com/Spico197/DocEE/blob/c6640b3c6559868203b46496fa721ec8e76653c1/Data/DuEEData/build_data.py#L240-L247

**Comment by zlh-source** [comment]
好的 感谢您的回复！
