### ISSUE TITLE
请问训练duee-fin大概需要的算力规模和时间是多少呢？

### ISSUE THREAD

**Issue by catcatcatll** [Spico197/DocEE#35]
运行了老师您提供的模型参数 ，应该是在ChinFIn上训练的吧。我想问一下现在想在duee-fin上训练，但是我的硬件设备有限，请问大概需要多长时间呢？

**Comment by Spico197** [comment]
感谢对本项目的关注。您指的是PTPCG吧？在V100上训练DuEE-fin的话大概要单卡跑8小时。显存占用大概是在11GB以内。

**Comment by xxllp** [comment]
不知道这个几个数据集的效果是否能给出来
