### ISSUE TITLE
关于filter_event_type的unk参数，以及寻求一些建议

### ISSUE THREAD

**Issue by BEILOP** [Spico197/DocEE#36]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [ x] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [x ] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [x ] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [x ] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem

您好，我的问题1：:在最新的inference.py里我发现filter_event_type里出现了个unk，这个是在什么情况使用，我记得之前只支持o2o,o2m,m2m.overall
问题2：您对于开放域的中文新闻中的事件检测模型有什么了解或者推荐么？由于新闻的表达多样性和数据分布，无法直接使用您的模型预测。仍然会预测出大量错误的事件（不含事件的、其他语义类似事件但未包括在已定义事件错分为定义的事件，所以需要在前置加入事件检测部分。
     我目前使用了触发词触发事件（保证不筛入完全不含事件的情况，但可能产生大量误召回以及筛掉含部分未收录触发词的已定义事件）+后续根据您的模型抽取结果和文章向量卡阈值的方法（筛出低置信度的结果，保证已抽出结果准确性），但依旧没能解决

## Environment

| Environment               | Values        |
| :------------------------ | :------------ |
| System                    | Windows/Linux |
| GPU Device                |               |
| CUDA Version              |               |
| Python Version            |               |
| PyTorch Version           |               |
| dee (the Toolkit) Version |               |

## Full Log

```
Log:

```

**Comment by Spico197** [comment]
嗨您好，感谢对本项目的关注。
1. 之前是`o2o,o2m,m2m`，`unk`仅在推理阶段有用。因为在推理阶段是不知道文本有多少个实例的，所以用`unk`来表示
2. 您指的是开放域事件抽取“检测”吗（带触发词的）？那应该不涉及事件表填充的内容。我的个人理解是open-domain event detection只是type不定形，如果有触发词的话，那就是更像一个触发词抽取任务

**Comment by BEILOP** [comment]
感谢您的回答。
很抱歉表达不够清晰，按照您的理解，确实是偏向触发词抽取+篇章事件预分类放在前面，筛出来的过事件抽取模型做要素提取。我们定义了100多类定形的type事件，在新闻篇章里抽取，数据每类有100-1000条。
由于以下原因，需要在事件抽取模型前加这一步：
1、分批标的数据，上的模型，且后续新增事件不可以影响之前准确率，所以训练了多个DocEE事件抽取模型
2、直接使用DocEE，由于新闻的多样性，难以构造不含事件或者  含在定义事件外的其他事件  ，但是可能包含触发词、公司名、人名等事件内容的Other类样本。
3、m2m的真实数据很多，但事件类型太多对标注来说很麻烦。所以想把经常一起出现的做在一个模型，每次只标注十几类事件。从而减轻标注负担，由预分类去分流到多个模型预测后整合。
但有以下这些状况：
1、部分事件触发词是难以涵盖完全；2、触发词会不连续；3、新闻数据复杂，预分类也无法覆盖大量负样本；
4、如前所述，包含触发词但不是所需事件。
不知道您有无什么推荐，或者什么思路我去实现一波。再次感谢。

**Comment by Spico197** [comment]
从您的回答来看，您的需求不算是开放域，只是类别多了点。
我建议您不要在这里用端到端模型，可以把里面的模块拆开试试，方便调试。
事件分类可以用其它分类模型，不连续/重叠的触发词抽取可以用相关的NER模型代替。仅使用PTPCG做事件论元的组合。
如果是有触发词且篇章长度不长的话，可以尝试借鉴使用句子级的事件抽取方案。

**Comment by Spico197** [comment]
此外如果事件类别是可增长的话，建议把分类模型改成matching类的模式。
或者prompting+trie也可以，不过好像没人在长篇章上做过prompting，可靠性存疑。

**Comment by BEILOP** [comment]
好的，非常感谢您的建议，我去尝试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tong ***@***.***&gt;; 
发送时间: 2022年6月7日(星期二) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Spico197/DocEE] 关于filter_event_type的unk参数，以及寻求一些建议 (Issue #36)





 
此外如果事件类别是可增长的话，建议把分类模型改成matching类的模式。
 或者prompting+trie也可以，不过好像没人在长篇章上做过prompting，可靠性存疑。
