### ISSUE TITLE
How to generate "dueefin_PTPCG_P1R1_wTgg.json" or Where is "dueefin_PTPCG_P1R1_wTgg.json" or What's its  format

### ISSUE THREAD

**Issue by TinaGioro** [Spico197/DocEE#39]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [x] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [xx] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [x] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [x] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

## Problem
When I train the code about dueefin, I can't find  dueefin_PTPCG_P1R1_wTgg.json file.  My question is what the title says. Thanks for reading! Looking forward to your reply!

**Comment by Spico197** [comment]
Hi, these files are generated during inferencing the submit files (the inferenced results), and they will be generated after the training process.
Please provide the executive script and the whole training log if any error occurs.

**Comment by TinaGioro** [comment]
Thanks for replying! 
Just now I found the following setting in dee_task.py:      
  elif self.run_mode == "dueefin_w_tgg":
            self.train_file_name = "dueefin_train_w_tgg.json"
            self.dev_file_name = "dueefin_dev_w_tgg.json"
            self.test_file_name = "dueefin_dev_w_tgg.json"
            self.inference_file_name = "dueefin_submit_w_tgg.json"
            self.doc_lang = "zh"
So no error will occur. But why you set self.test_file_name = "dueefin_dev_w_tgg.json"？ Is it useless?

**Comment by Spico197** [comment]
By setting `self.test_file_name = "dueefin_dev_w_tgg.json"`, we could keep the program's logic unchanged across different datasets. Otherwise we have to change the training procedure for those that do not own an official test set.
