### ISSUE TITLE
训练模型对计算资源的要求

### ISSUE THREAD

**Issue by Rover912** [Spico197/DocEE#4]
感谢分享。请问卡数的要求和限制（如：Tip: At least 4 * NVIDIA V100 GPU (32GB) cards are required to run GIT models.）是为了训练速度考虑吗，还是对模型训练后的表现也有影响？

降低Batch_size或者增加梯度累计可以用更少的资源来训练（虽然训练时间更长了），不知道作者有没有试过这样做对最终模型效果的影响

**Comment by Spico197** [comment]
嗨，感谢您对本项目的关注。这里关于Doc2EDAG和GIT的tips主要是为了和原始repo中的相统一，从而方便大家复现出和论文中相等或相当的结果。咱们当然可以根据自己的硬件情况做相应的调整，不过不保证精度上是否还能达到相当的性能。
Doc2EDAG和GIT的原始repo中也有人问相关的问题，您可以参考一下：

- [Doc2EDAG #25](https://github.com/dolphin-zs/Doc2EDAG/issues/25)
- [GIT #5](https://github.com/RunxinXu/GIT/issues/5)

**Comment by Rover912** [comment]
> 

嗯嗯，感谢~
