### ISSUE TITLE
where to download bert-base-chinese

### ISSUE THREAD

**Issue by KgLearner** [Spico197/DocEE#40]
## Agreement

- [x] Fill the space in brackets with `x` to check the agreement items.
- [x] Before submitting this issue, I've fully checked the instructions in `README.md`.
- [x] Before submitting this issue, I'd searched in the issue area and didn't find a solved issue that covers my problem.
- [x] This issue is about the toolkit itself, not Python, pip or other programming basics.
- [x] I understand if I do not check all the agreemnt items above, my issue ***MAY BE CLOSED OR REMOVED WITHOUT FURTHER EXPLANATIONS***.

Hi, I am trying to train PTPCG. I download bert-base-chinese from huggingface website but error occurs.  So I want to get your bert model to reduce the probability of errors. Thanks for reading.

**Comment by Spico197** [comment]
I downloaded the model from huggingface, too. Or, if you just want to reproduce the results in our paper, just download the `vocab.txt` file since we don't actually use the PLM weights.

**Comment by TinaGioro** [comment]
Thanks for replying! I will try again!
