### ISSUE TITLE
How can PTPCG be used for news event extraction 

### ISSUE THREAD

**Issue by TinaGioro** [Spico197/DocEE#41]
Hi,I will use PTPCG for news event extraction. The data format has been processed into PTPCG input format.  And I have used trigger.py to get the importance score of psudo trigger selection. Do I need to modify other places besides? like utils.py of dee folder. And what other details should I pay attention to....   
Thanks for reading! I am looking forward to your replying!

**Comment by Spico197** [comment]
You may want to:
1. generate a new event type template in `dee/event_types`
2. add a run mode in `dee/tasks/dee_task.py/DEETaskSetting`
3. change corresponding `run_mode` and `template` in the executive script
