### ISSUE TITLE
预测结果出错

### ISSUE THREAD

**Issue by KgLearner** [Spico197/DocEE#42]

**Comment by Spico197** [comment]
预测单字的问题我也遇到过，可以先检查下代码，模型权重有没有正常导入？

**Comment by KgLearner** [comment]
老师，您好，我下载了您task_tump后使用inference.py预测结果是正确的。
但如果我根据您的repo步骤训练后再使用Inference.py预测仍然出现单字的问题。请问模型权重的导入是指的哪一块，谢谢老师！
