### ISSUE TITLE
doc_lang=self.setting.doc_lang报错

### ISSUE THREAD

**Issue by DreamingFuture** [Spico197/DocEE#44]
在运行run_ptpcg_dueefin_withtgg_withptgg.sh时，报错 self.setting没有doc_lang这个值，然后我手动加了一下（俺也不知道对不对，添加的值是self.setting.doc_lang=‘zh’）

**Comment by Spico197** [comment]
Hi，抱歉刚刚看到消息。
您是对的。我检查了一下代码，只有这个mode下会出现语言值缺失的问题。如下所示，在276行下面添加`self.doc_lang = "zh"`即可。

https://github.com/Spico197/DocEE/blob/9f0538a937c48b5b4ee8ed3c9394f993d6c10fce/dee/tasks/dee_task.py#L266-L276

**Comment by Spico197** [comment]
已修正，非常感谢您~

**Comment by DreamingFuture** [comment]
啊hhh没事没事，小白能发现问题很开心！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Spico197/DocEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Spico197/DocEE] doc_lang=self.setting.doc_lang报错 (Issue #44)





 
已修正，非常感谢您~
