### ISSUE TITLE
PTPCG预测时灵活性的问题

### ISSUE THREAD

**Issue by Rover912** [Spico197/DocEE#5]
hi，看了PTPCG这个模型，对预测过程有个问题。假设邻接矩阵已经预测出来，那么对应的Combinations也就确定了，下面就要根据每一个预测出的事件类型和Combinations里的每一个Combination进行论元角色预测。这样是不是有一个潜在的假设：每一个预测出的事件类型都有同样数量的Combination，即每个event_type都有同样数量的event_object。不知道我的理解是否有误？

**Comment by Spico197** [comment]
嗨，感谢您对PTPCG的关注。

不是这样的。组合的数量是不固定的，每个事件类型预测出的组合当然也是不固定的。如论文所述，这里虽然做了笛卡尔积的操作，但在特定事件类别的前提下，并不是每一个候选类别都能得到对应的组合。如果预测论元角色时为空（每个论元都不能承担任意一个角色），那么这个事件实例自然也就不存在了。这一步是在 event table中角色预测解码时来实现的。

**Comment by Rover912** [comment]
> 

感谢回答。我是不是可以这么理解：在角色预测解码之前，每一个预测出的event_type对应的Combinations都一样（因为邻接矩阵不随事件类型的变化而变化），即Combinations包含相同数量的Combination且每一个Combination中含有相同的实体。但是在对特定的event_type进行角色预测解码时，可能会预测出某个Combination对应的角色均为空，这时就会舍弃这个Combination，即舍弃了一个event_object。

**Comment by Spico197** [comment]
是的，您的理解没错。其实也可以把模型改成事件类别和组合对应，即每个事件类别都参与组合的预测，从而得到不同的组合。我们尝试过这种方法，不过没有得到太大的收益，反而增加了不少模型参数，所以最后还是使用了现在的这种方法，即事件类别和组合无关。

**Comment by Rover912** [comment]
嗯嗯，感觉这种从全图中找子图的思路挺有意思的。不知道您看过[Exploring Sentence Community for Document-Level Event Extraction](https://aclanthology.org/2021.findings-emnlp.32/)这篇没有，也是利用了community detection的思想，只不过是在句子层面上，PTPCG是在实体层面上。

**Comment by Spico197** [comment]
关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。

**Comment by Rover912** [comment]
> 关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。

我的疑惑是他们构建目标句子社区的时候，是假设知道即将有C个事件将要预测出来，所以构建了C*N的矩阵。而预测的时候，其实是不知道有几个事件的。这就有点迷了。

**Comment by Spico197** [comment]
> 关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。

之前的这个回答可能偏离了您的问题，我再补充一下。sentence community detection的过程和PTPCG的方法在思想上是有相似之处的，不过在具体做法上类似于DE-PPN，即预先设置事件实例的数量。这里他们利用句子来定位具体是哪些实体，通过两步走的方式产生实例，这样就可以充分利用边的连接关系了。

**Comment by Spico197** [comment]
> > 关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。
> 
> 
> 
> 我的疑惑是他们构建目标句子社区的时候，是假设知道即将有C个事件将要预测出来，所以构建了C*N的矩阵。而预测的时候，其实是不知道有几个事件的。这就有点迷了。

我猜测这里应该是固定了C的数量，预测时根据第二步角色分类再做进一步筛选。不过作者似乎没有放出代码，所以只是猜测。

**Comment by Spico197** [comment]
具体关于SCDEE的问题还需要和论文作者做进一步沟通。因为没看到代码，所以我确实没办法解释与之相关的一些问题，希望您能理解。

**Comment by RunxinXu** [comment]
> > 关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。
> 
> 我的疑惑是他们构建目标句子社区的时候，是假设知道即将有C个事件将要预测出来，所以构建了C*N的矩阵。而预测的时候，其实是不知道有几个事件的。这就有点迷了。

+1

**Comment by Rover912** [comment]
> > 关于这篇工作我有很多问题，发信给作者之后还没收到回复。但从论文中理解的话，他们构建的应该是一个固定的图（类似GIT中提到的方法），而PTPCG是还原一个不固定的图，编码时不能将边的连接关系提前泄露。另外我一直不清楚他们效果的提升是不是BERT带来的，所以一直有些疑惑。不知道我的理解是不是正确，欢迎更多的朋友参与自由讨论。
> 
> 之前的这个回答可能偏离了您的问题，我再补充一下。sentence community detection的过程和PTPCG的方法在思想上是有相似之处的，不过在具体做法上类似于DE-PPN，即预先设置事件实例的数量。

我也感觉是应该是设定好了事件实例的数量。细节可能要作者来解释了：）。感谢～
