### ISSUE TITLE
在计算相似度时是否忽略了实体的相对位置

### ISSUE THREAD

**Issue by TinaGioro** [Spico197/DocEE#54]
** Idea sharing **
While sharing what you want to do, make sure to protect your ideas.

** Problems **
请问得到了Entities后是否抛弃了实体所在位置。
对于该句子“2021年接到报警，王小明于2019年在xx路持刀伤人。”如果忽略了相对位置，是否分不清2021年和2019年是属于哪个事件类型的论元。

** Others **
Other things you may want to share or discuss.

**Comment by Spico197** [comment]
1. 是的，抛弃了位置。因为是基于文本的评价，所以位置在这里不重要，只要文本上区分就行；
2. 不会。因为2021年和2019年是不一样的文本。
