### ISSUE TITLE
Transformer相关的问题

### ISSUE THREAD

**Issue by logolemon** [Spico197/DocEE#57]
老师您好，读您的论文，看您将所有的BiLSTM层替换为transformer的，这个在您的代码里应该如何实现，

**Comment by Spico197** [comment]
感谢您对本项目的关注。PTPCG模型实现的代码在 `dee/models/trigger_aware.py/TriggerAwarePrunedCompleteGraph` 中，主要继承了 `dee/models/lstmmtl2complete_graph.py/LSTMMTL2CompleteGraphModel`。关于用于实体再编码的 `span_lstm` 和 `mention_lstm` ，您可以替换成 `dee/modules/transformer.py` 中的 encoder 模块。对于要素抽取和事件表示，因为用了双向 LSTM 头尾位置表示拼接作为句子表示，您只需要按 Doc2EDAG 一样对全句表示做 max-pooling 即可。

**Comment by logolemon** [comment]
好的 老师谢谢您的解答
