### ISSUE TITLE
some doubts

### ISSUE THREAD

**Issue by OPilgrim** [Spico197/DocEE#59]
I haven't read your code in detail, so I would like to ask for some advice in case I make mistakes later. I would like to ask, what is the difference between these two commands, or more specifically, why set the `one pseudo trigger` when you already have a `annotated trigger`?

```
# run on DuEE-fin dataset with annotated trigger and without pseudo trigger (to reproduce |R|=0, Tgg=√ results in Table 3 of the PTPCG paper)
$ nohup bash scripts/run_ptpcg_dueefin_withtgg.sh 1>Logs/PTPCG_T1-DuEE_fin.log 2>&1 &
$ tail -f Logs/PTPCG_T1-DuEE_fin.log

# run on DuEE-fin dataset with annotated trigger and one pseudo trigger (to reproduce |R|=1, Tgg=√ results in Table 3 of the PTPCG paper)
$ nohup bash scripts/run_ptpcg_dueefin_withtgg_withptgg.sh 1>Logs/PTPCG_P1T1-DuEE_fin.log 2>&1 &
$ tail -f Logs/PTPCG_P1T1-DuEE_fin.log
```

**Comment by Spico197** [comment]
Thanks for the question.
Under the pruned complete graph setting, there could be more than one triggers, no matter they are pseudo or manually annotated.
In this case, we would like to figure out what would happen if we use both the annotated trigger and the pseudo trigger.
More details could be found in the original PTPCG paper.
