### ISSUE TITLE
Would it be possible to use my own entities?

### ISSUE THREAD

**Issue by demongolem-biz** [Spico197/DocEE#6]
I have my own entities extracted through another model.  How easy would it be to apply DEE to these external entities using this work?  I see that the entities and events share an lstm at the beginning of processing.

**Comment by Spico197** [comment]
Hi, there. Do you mean you want to 1) `skip the entity extraction part` and use extracted entities directly or 2) add additional entities while training?

**Comment by demongolem-biz** [comment]
First.  Skip entity extraction because I already have my own entities
detected and these entities come from a custom set of entity classes.

-Greg

**Comment by Spico197** [comment]
I see. You can follow the steps as below:

1. Build your own dataset which includes all the entities extracted by another model.
2. Change the event template in `dee/event_types`. Add the customised entity type into `common_fields` (or `FIELDS` if you have your own event template).
3. Train the model. If you don't want to do the NER part again, change the `get_mix_loss` function in model files.
4. During evaluation (prediction), make sure you pass the `use_gold_span=True` when calling `model.forward` function.

**Comment by Spico197** [comment]
I'd like to close this inactive issue. Feel free to open it if the above discussion does not solve your question.
