### ISSUE TITLE
代码疑似错误

### ISSUE THREAD

**Issue by iamqiz** [Spico197/DocEE#60]
https://github.com/Spico197/DocEE/blob/2a323b0ee171f578d4c00e1b7c7c450f296306bd/Data/DuEEData/build_data.py#L255-L259

len(et_counter) == 0 and et_counter[0]

**Comment by Spico197** [comment]
您好，感谢您对本项目的关注。可以再详细说说吗？

这段代码主要是帮助确定当前文档的类型：
- 如果包含多个事件类别，则为`m2m`
- 如果包含一个事件类别的一个事件实例，则为`o2o`
- 如果包含一个事件类别的多个事件实例，则为`o2m`

从代码逻辑上，我没有发现可能存在的错误，麻烦您再详细解释一下？

**Comment by iamqiz** [comment]
len(et_counter) == 0 了 怎么还能 et_counter[0] ?

**Comment by Spico197** [comment]
谢谢您的指正，确实是写岔了，当时看了几遍竟然没看出来orz。马上修改。

**Comment by Spico197** [comment]
抱歉给大家带来困扰了，已更新代码。再次感谢您的贡献和帮助。祝元旦快乐！
