### ISSUE TITLE
请问可以提供各个模型的checkpioint吗？

### ISSUE THREAD

**Issue by kelvennn** [Spico197/DocEE#62]
GIT等模型计算代价实在太大了

**Comment by Spico197** [comment]
抱歉，GIT等模型是在合作方机器上训练的。受公司条约限制，我也没办法拿到权重，只能获取到指标结果。

**Comment by kelvennn** [comment]
好的，谢谢大佬的回复

那我想请问一下还有GIT等模型的训练日志可供参考吗？想知道通过前10epoch猜测比如Doc2EDAG等模型训练速度是否可靠？因为似乎他们的预测、训练的速度受有向图生成影响，在不同的生成EDAG能力下（训练初期与模型具备了可接受的效果）是更快还是更慢呢？？？

因为前10epoch下，我好像训练GIT比Doc2EDAG更快，哈哈哈

**Comment by Spico197** [comment]
当时做的实验有点多，现在对应不太上了。不过找到了Doc2EDAG和GIT的某次实验结果的日志。硬软件平台是相同的，所以可以做速度对比。这个只是中间某次的试验结果，最终评价部分数值可能和论文中汇报不相符，仅供速度参考。

加油加油加油！

[git_training.log](https://github.com/Spico197/DocEE/files/10988677/git_training.log)
[doc2edag_training.log](https://github.com/Spico197/DocEE/files/10988678/doc2edag_training.log)

**Comment by kelvennn** [comment]
非常感谢！
