### ISSUE TITLE
怎么加bert模型呢

### ISSUE THREAD

**Issue by guocxian** [Spico197/DocEE#63]
Before running any bash script, please ensure bert_model has been correctly set.

能具体解释下吗？

**Comment by guocxian** [comment]
thanks

**Comment by Spico197** [comment]
您好，因为这些模型使用的都是BERT的词表，所以需要给出BERT文件夹的位置，并修改[这里](https://github.com/Spico197/DocEE/blob/af501b6077840606fffab7b0325a05c8b8101df6/scripts/run_ptpcg.sh#L27)的配置地址。

如果是想在模型的层面使用BERT的权重，可以直接把[这行](https://github.com/Spico197/DocEE/blob/af501b6077840606fffab7b0325a05c8b8101df6/scripts/run_ptpcg.sh#L26)改成`True`。

**Comment by guocxian** [comment]
谢谢您！

在 2023年5月2日星期二，Tong Zhu (朱桐) ***@***.***> 写道：
