### ISSUE TITLE
Number of gold arguments for ChFinAnn

### ISSUE THREAD

**Issue by donovanOng** [Spico197/DocEE#64]
** Problems **

How many gold arguments are used to calculate the P/R/F1 for ChFinAnn reported in the paper?

**Comment by Spico197** [comment]
The number of gold arguments in PTPCG is the same as other baselines that use ChFinAnn.
You can download the original data from [here](https://github.com/dolphin-zs/Doc2EDAG/blob/master/Data.zip) and get the statistics.

**Comment by Spico197** [comment]
Hi there, does my response answer your questions? I'd like to close this issue if there's no further discussion.

**Comment by donovanOng** [comment]
Hi @Spico197 after training the model on ChFinAnn, the test data arguments TP+FN = 28,545 but when I count the arguments from the original test data, it is 29,345.

I traced the missing arguments and found that they are dropped during the truncation of sentences and documents. Can you confirm?

Thanks.

**Comment by Spico197** [comment]
Yes. The default setting of the number of sentences in a document is 64, while the max sequence length is 128, so some documents are trucated. Doc2EDAG, GIT, PTPCG use the same setting. It may be potentially unfair if you use other settings.

**Comment by Spico197** [comment]
I didn't check the exact numbers yet, but do you mean arguments instead of mentions or entities?

**Comment by donovanOng** [comment]
yes, I mean the arguments in event tables

**Comment by Spico197** [comment]
I understand. I'll try to get the statistics soon.

**Comment by donovanOng** [comment]
@Spico197 Hi! Would you be able to share the model predictions for ChFinAnn and DuEE-fin dev? I really appreciate your valuable time.

**Comment by Spico197** [comment]
Hi there, sorry for the late response. Things been busy these days.

The attachment below contains:
- PTPCG test evaluation results on ChFinAnn Epoch=57 (you can calculate the number of arguments from TP, FP and FNs in overall/overall) and middle prediction outputs.
- PTPCG dev evaluation results and middle prediction outputs on DuEE-Fin Epoch=99

[PTPCG-MiddleResults.zip](https://github.com/Spico197/DocEE/files/11767440/PTPCG-MiddleResults.zip)

**Comment by Spico197** [comment]
In case of any inconvenience for your analysis, I updated the PTPCG task dump trained on DuEE-Fin.
You can find it here: https://github.com/Spico197/DocEE/releases/tag/tasks-ptpcg-dueefin

**Comment by donovanOng** [comment]
Thanks a lot!
