### ISSUE TITLE
请问怎么查看到中文格式的事件预测结果？

### ISSUE THREAD

**Issue by cathyry** [Spico197/DocEE#65]
你好呀，训练模型后的输出有一个Output文件夹，里面有json和pkl两种格式的文件，pkl里面格式是mention_drange_list，event_dag_info这种的，而且是编码格式，怎么看到有对应中文跨度的事件预测结果啊

**Comment by Spico197** [comment]
您好，输出文件夹中的内容仅包含一些用于评价的中间结果。如果想获得完整的事件预测结果，可以参考项目中提供的推理接口：https://github.com/Spico197/DocEE/blob/main/inference.py

**Comment by cathyry** [comment]
> 您好，输出文件夹中的内容仅包含一些用于评价的中间结果。如果想获得完整的事件预测结果，可以参考项目中提供的推理接口：https://github.com/Spico197/DocEE/blob/main/inference.py

好的，但是现在遇到了新的问题，inference.py预测结果中的argument只有一个字

**Comment by Spico197** [comment]
这个问题比较复杂，需要排查是模型预测结果本身的问题还是预测接口的问题。

1. 使用的是什么模型
2. 数据集是什么
3. load的模型的NER结果如何
4. 有没有尝试从推理接口回溯debug，一些中间结果是什么

**Comment by Spico197** [comment]
Hi 您好，请问您的问题解决了吗

**Comment by cathyry** [comment]
> Hi 您好，请问您的问题解决了吗

感谢您的关注，问题已经解决了，为了节省存储空间，我并没有保存每次epoch的模型结果，只保存了当前的best模型，在inference中设置了错误的模型epoch数，设置为best模型的完整正确名称后，输出正常了

**Comment by Spico197** [comment]
好嘞，谢谢您的反馈~
