### ISSUE TITLE
您好，问一下一个论元角色多个实体的如何体现在数据并预测？另外最近有什么新的关于事件的研究进展么？

### ISSUE THREAD

**Issue by BEILOP** [Spico197/DocEE#66]
您好，问一下一个论元角色多个实体的如何体现在数据并预测？另外最近有什么新的关于事件的研究进展么？

**Comment by Spico197** [comment]
嗨您好，抱歉刚刚看到issue的消息。角色—论元一对多的情况可以参考这个issue里的回复：https://github.com/Spico197/DocEE/issues/38#issuecomment-1176207177

最新的事件抽取研究进展可以关注最近公开的ACL23 pub list，有一些DocEE的相关工作。我们会在他们公开代码之后，将论文里的方法纳入到这个工具里来。

**Comment by WindSearcher** [comment]
请问下大佬，目前文档级别事件抽取，有试过大模型嘛。我感觉目前文档级别事件抽取传统方法应该更好点，但又想结合下大模型，不知道这方面大佬了解嘛

**Comment by WindSearcher** [comment]
> 嗨您好，抱歉刚刚看到issue的消息。角色—论元一对多的情况可以参考这个issue里的回复：[#38 (comment)](https://github.com/Spico197/DocEE/issues/38#issuecomment-1176207177)
> 
> 最新的事件抽取研究进展可以关注最近公开的ACL23 pub list，有一些DocEE的相关工作。我们会在他们公开代码之后，将论文里的方法纳入到这个工具里来。

请问下大佬，目前文档级别事件抽取，有试过大模型嘛。我感觉目前文档级别事件抽取传统方法应该更好点，但又想结合下大模型，不知道这方面大佬了解嘛
