### ISSUE TITLE
无法使用GPU

### ISSUE THREAD

**Issue by WindSearcher** [Spico197/DocEE#68]
![Uploading 图片.png…]()
同样一个conda虚拟环境，我的另外一个项目使用到GPU，而这个项目运行scripts/run_ptpcg.sh却走的CPU

**Comment by Spico197** [comment]
您好，感谢对本项目的关注。您的图片没有上传完，看不到您的输出。能否提供一个完整的log？另外您看下这里第12行的环境变量是否为您所用卡的正确设置：

https://github.com/Spico197/DocEE/blob/a32b6f8bf0b2fe28b9942b0b53eff461abf561ba/scripts/run_ptpcg.sh#L12-L26

**Comment by WindSearcher** [comment]
> 您好，感谢对本项目的关注。您的图片没有上传完，看不到您的输出。能否提供一个完整的log？另外您看下这里第12行的环境变量是否为您所用卡的正确设置：
> 
> https://github.com/Spico197/DocEE/blob/a32b6f8bf0b2fe28b9942b0b53eff461abf561ba/scripts/run_ptpcg.sh#L12-L26

本项目运行：
<img width="1016" alt="image" src="https://github.com/Spico197/DocEE/assets/33864192/d2025080-d700-4cc7-9dc4-9b563ddcc340">
<img width="934" alt="image" src="https://github.com/Spico197/DocEE/assets/33864192/db656130-db33-4fa7-a0d2-38a2c0d13436">

其它项目运行：
<img width="1017" alt="image" src="https://github.com/Spico197/DocEE/assets/33864192/a11a26b4-3f47-4f19-ad8b-e3f3e22359fb">

**Comment by Spico197** [comment]
您好，感谢您的反馈。我想先确认一下：
1. 服务器上卡1可不可用（`cuda:1`）
2. 切换成bash启动是否可行：`bash scripts/run_ptpcg.sh`

**Comment by WindSearcher** [comment]
> 您好，感谢您的反馈。我想先确认一下：
> 
> 1. 服务器上卡1可不可用（`cuda:1`）
> 2. 切换成bash启动是否可行：`bash scripts/run_ptpcg.sh`

万分感谢您，我的卡号应该是0

**Comment by Spico197** [comment]
好嘞您再试试，可以等跑起来了再关issue。后续问题欢迎继续留言讨论~

**Comment by WindSearcher** [comment]
> 好嘞您再试试，可以等跑起来了再关issue。后续问题欢迎继续留言讨论~

好的，感谢大佬
