### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by WindSearcher** [Spico197/DocEE#69]
{
	"task_name": "PTPCG_R1_reproduction",
	"total_results": [{
		"ModelType": "TriggerAwarePrunedCompleteGraph",
		"Average": {
			"precision": "82.8",
			"recall": "69.1",
			"f1": "75.2"
		},
		"Total": {
			"precision": "83.9",
			"recall": "72.7",
			"f1": "77.9"
		},
		"EquityFreeze": {
			"precision": "85.5",
			"recall": "60.1",
			"f1": "70.6"
		},
		"EquityRepurchase": {
			"precision": "93.4",
			"recall": "87.4",
			"f1": "90.3"
		},
		"EquityUnderweight": {
			"precision": "79.2",
			"recall": "62.6",
			"f1": "70.0"
		},
		"EquityOverweight": {
			"precision": "74.6",
			"recall": "65.8",
			"f1": "69.9"
		},
		"EquityPledge": {
			"precision": "81.2",
			"recall": "69.8",
			"f1": "75.1"
		}
	}],
	"sm_results": [{
		"ModelType": "TriggerAwarePrunedCompleteGraph",
		"Average": {
			"Single": "84.0",
			"Multi": "62.5"
		},
		"Total": {
			"Single": "88.0",
			"Multi": "66.2"
		},
		"EquityFreeze": {
			"Single": "83.7",
			"Multi": "57.8"
		},
		"EquityRepurchase": {
			"Single": "92.5",
			"Multi": "70.4"
		},
		"EquityUnderweight": {
			"Single": "78.4",
			"Multi": "57.5"
		},
		"EquityOverweight": {
			"Single": "78.4",
			"Multi": "59.1"
		},
		"EquityPledge": {
			"Single": "87.1",
			"Multi": "67.8"
		}
	}],
	"pred_results": [{
		"ModelType": "TriggerAwarePrunedCompleteGraph",
		"o2o": {
			"classification": {
				"precision": "99.216",
				"recall": "99.586",
				"f1": "99.400"
			},
			"entity": {
				"precision": "97.416",
				"recall": "99.283",
				"f1": "98.341"
			},
			"combination": {
				"precision": "48.911",
				"recall": "53.958",
				"f1": "51.310"
			},
			"rawCombination": {
				"precision": "48.660",
				"recall": "54.911",
				"f1": "51.597"
			},
			"overall": {
				"precision": "87.386",
				"recall": "88.544",
				"f1": "87.961"
			},
			"instance": {
				"precision": "45.437",
				"recall": "50.145",
				"f1": "47.675"
			}
		},
		"o2m": {
			"classification": {
				"precision": "98.836",
				"recall": "98.708",
				"f1": "98.772"
			},
			"entity": {
				"precision": "97.095",
				"recall": "99.224",
				"f1": "98.148"
			},
			"combination": {
				"precision": "20.264",
				"recall": "17.569",
				"f1": "18.821"
			},
			"rawCombination": {
				"precision": "17.619",
				"recall": "16.160",
				"f1": "16.858"
			},
			"overall": {
				"precision": "79.002",
				"recall": "57.132",
				"f1": "66.310"
			},
			"instance": {
				"precision": "16.658",
				"recall": "14.354",
				"f1": "15.421"
			}
		},
		"m2m": {
			"classification": {
				"precision": "100.000",
				"recall": "59.459",
				"f1": "74.576"
			},
			"entity": {
				"precision": "95.430",
				"recall": "96.467",
				"f1": "95.946"
			},
			"combination": {
				"precision": "26.923",
				"recall": "17.500",
				"f1": "21.212"
			},
			"rawCombination": {
				"precision": "25.000",
				"recall": "17.500",
				"f1": "20.588"
			},
			"overall": {
				"precision": "83.146",
				"recall": "40.437",
				"f1": "54.412"
			},
			"instance": {
				"precision": "14.815",
				"recall": "10.000",
				"f1": "11.940"
			}
		},
		"overall": {
			"classification": {
				"precision": "99.130",
				"recall": "98.914",
				"f1": "99.022"
			},
			"entity": {
				"precision": "97.300",
				"recall": "99.245",
				"f1": "98.263"
			},
			"combination": {
				"precision": "36.676",
				"recall": "36.156",
				"f1": "36.414"
			},
			"rawCombination": {
				"precision": "35.147",
				"recall": "35.965",
				"f1": "35.551"
			},
			"overall": {
				"precision": "83.915",
				"recall": "72.720",
				"f1": "77.917"
			},
			"instance": {
				"precision": "33.097",
				"recall": "32.545",
				"f1": "32.819"
			}
		}
	}],
	"gold_results": [{
		"ModelType": "TriggerAwarePrunedCompleteGraph",
		"o2o": {
			"classification": {
				"precision": "99.216",
				"recall": "99.586",
				"f1": "99.400"
			},
			"entity": {
				"precision": "100.000",
				"recall": "100.000",
				"f1": "100.000"
			},
			"combination": {
				"precision": "78.084",
				"recall": "82.097",
				"f1": "80.040"
			},
			"rawCombination": {
				"precision": "74.558",
				"recall": "78.574",
				"f1": "76.513"
			},
			"overall": {
				"precision": "93.462",
				"recall": "95.913",
				"f1": "94.671"
			},
			"instance": {
				"precision": "74.173",
				"recall": "78.077",
				"f1": "76.075"
			}
		},
		"o2m": {
			"classification": {
				"precision": "98.836",
				"recall": "98.708",
				"f1": "98.772"
			},
			"entity": {
				"precision": "100.000",
				"recall": "100.000",
				"f1": "100.000"
			},
			"combination": {
				"precision": "31.789",
				"recall": "28.093",
				"f1": "29.827"
			},
			"rawCombination": {
				"precision": "27.365",
				"recall": "24.835",
				"f1": "26.039"
			},
			"overall": {
				"precision": "82.653",
				"recall": "66.508",
				"f1": "73.707"
			},
			"instance": {
				"precision": "28.550",
				"recall": "25.077",
				"f1": "26.701"
			}
		},
		"m2m": {
			"classification": {
				"precision": "100.000",
				"recall": "59.459",
				"f1": "74.576"
			},
			"entity": {
				"precision": "100.000",
				"recall": "100.000",
				"f1": "100.000"
			},
			"combination": {
				"precision": "37.500",
				"recall": "30.000",
				"f1": "33.333"
			},
			"rawCombination": {
				"precision": "46.667",
				"recall": "35.000",
				"f1": "40.000"
			},
			"overall": {
				"precision": "66.935",
				"recall": "45.355",
				"f1": "54.072"
			},
			"instance": {
				"precision": "29.412",
				"recall": "25.000",
				"f1": "27.027"
			}
		},
		"overall": {
			"classification": {
				"precision": "99.130",
				"recall": "98.914",
				"f1": "99.022"
			},
			"entity": {
				"precision": "100.000",
				"recall": "100.000",
				"f1": "100.000"
			},
			"combination": {
				"precision": "57.496",
				"recall": "55.694",
				"f1": "56.581"
			},
			"rawCombination": {
				"precision": "53.388",
				"recall": "52.371",
				"f1": "52.875"
			},
			"overall": {
				"precision": "88.639",
				"recall": "81.065",
				"f1": "84.683"
			},
			"instance": {
				"precision": "53.853",
				"recall": "52.068",
				"f1": "52.946"
			}
		}
	}]
}

您好，在ChFinAnn数据集上跑了30个epoch，没有看到论文实验结果的关于单事件和多事件的结果(precision、recall、f1)这些具体的指标，只看到了sm_results里面关于single和multi的一个值，不知道这个值对应的是啥。

**Comment by Spico197** [comment]
嗨您好，感谢对本项目的关注。

单事件和多事件的结果在`sm_results`里。`Single`表示单事件，`Multi`表示多事件。`Total`表示micro-averaged F1，`Average`表示macro-averaged F1.

**Comment by WindSearcher** [comment]
<img width="968" alt="image" src="https://github.com/Spico197/DocEE/assets/33864192/ed43c9c4-66b8-4b7d-9734-d3cb239d6b11">
感谢大佬的解答，但还是没有对齐这些指标，可以麻烦您对着这幅图，解答下sm_results中哪些结果是对应上面的ChFinAnn-Single和ChFinAnn-All的precision、recall、f1呢。

**Comment by Spico197** [comment]
- `ChFinAnn-Single`: 对应`pred_results/o2o/overall`;
- `ChFinAnn-All`: 对应`pred_results/overall/overall`.

**Comment by WindSearcher** [comment]
> 论文里这个图的结果和`pred_results/overall/overall`的结果对应。

感谢大佬
