### ISSUE TITLE
分布式训练

### ISSUE THREAD

**Issue by WindSearcher** [Spico197/DocEE#71]
您好，想请问下关于分布式训练ptpcg，如下图，在0和7卡上运行，但实际好像只在0卡上训练
<img width="473" alt="image" src="https://github.com/Spico197/DocEE/assets/33864192/ad3c8fd1-dfab-440f-8327-34596fab2171">

**Comment by WindSearcher** [comment]
看到了，run_ptpcg.sh可以参考train_multi.sh中的分布式训练

**Comment by WindSearcher** [comment]
具体脚本如下，把原先的这行注释，加上新的就行了
# CUDA_VISIBLE_DEVICES=${GPUS} python -u run_dee_task.py \
 CUDA_VISIBLE_DEVICES=${GPUS} python -m torch.distributed.launch --master_port=25662 --nproc_per_node ${NUM_GPUS} run_dee_task.py \

**Comment by WindSearcher** [comment]
`# CUDA_VISIBLE_DEVICES=${GPUS} python -u run_dee_task.py \

CUDA_VISIBLE_DEVICES=${GPUS} python -m torch.distributed.launch --master_port=25662 --nproc_per_node ${NUM_GPUS} run_dee_task.py \`
把原先的注释加上新的这一行即可

**Comment by Spico197** [comment]
最后还要加个 `--parallel_decorate` flag
