### ISSUE TITLE
deppn模型F1只有33

### ISSUE THREAD

**Issue by BudBudding** [Spico197/DocEE#73]
## Problem

您好，感谢您的工作！！
我正在您的工作上面复现deppn模型的效果，可是出现了问题。我运行的脚本文件是     run_deppn.sh  。由于我只有一个服务器，一张卡所以，我将这个脚本文件做了修改：
![image](https://github.com/Spico197/DocEE/assets/69427368/f3d5d817-e636-4360-9b8d-77bbee8fd085)
数据集按照您提供的进行放置，现在得到的结果为：
![image](https://github.com/Spico197/DocEE/assets/69427368/6dc83cf3-8385-4200-89eb-f303f184db76)
这个什么为什么呀？

**Comment by Spico197** [comment]
抱歉，本仓库实现的DEPPN目前还有些问题，请以DEPPN的[官方实现](https://github.com/HangYang-NLP/DE-PPN)为准

**Comment by BudBudding** [comment]
哦哦哦 好的 谢谢您的回复！
