### ISSUE TITLE
Duee_Fin预测结果

### ISSUE THREAD

**Issue by miraitowa9** [Spico197/DocEE#76]
您好，我想生成DueeFin测试集预测的标注结果，但是我有点没看懂关于readme中提到的event_table.py文件中的predict_span_role()方法，请问可以给一些提示我具体应该如何生成DueeFin测试集的预测结果吗？

**Comment by Spico197** [comment]
嗨您好，请问现在是已经训练好模型，打算基于这个模型预测线上结果吗？如果是的话，可以参考这个步骤：

1. 生成结果：如果是使用`run_ptpcg_dueefin.sh`这个脚本，结果已经自动生成了。如果是自定义的其它脚本，可以参考下面的一些配置。把`skip_train`和`load_inference`, `run_inference`设置为`True`，再指定一下生成文件的位置：`inference_dump_filepath`

https://github.com/Spico197/DocEE/blob/a32b6f8bf0b2fe28b9942b0b53eff461abf561ba/scripts/run_ptpcg_dueefin.sh#L56-L62

2. 结果后处理：因为生成的结果中有很多中间结果，需要做进一步的后处理。具体后处理脚本在下面这个位置，需要手动修改上一步生成的中间结果位置，以及最终结果的保存位置：

https://github.com/Spico197/DocEE/blob/a32b6f8bf0b2fe28b9942b0b53eff461abf561ba/dueefin_post_process.py#L101-L102

**Comment by miraitowa9** [comment]
非常感谢您的慷慨解答！！祝您科研顺利！！
