### ISSUE TITLE
测试集结果

### ISSUE THREAD

**Issue by WindSearcher** [Spico197/DocEE#77]
训练了两次，发现两次结果相差有点大，recall想差两个点左右。因为计算资源问题，我只跑了45个epoch，

**Comment by Spico197** [comment]
抱歉刚看到这条issue，因为有设置seed，所以这个现象还挺奇怪的。可能GPU有一些nondeterministic的加速策略，不过我目前没有特别好的解释orz

**Comment by WindSearcher** [comment]
> 抱歉刚看到这条issue，因为有设置seed，所以这个现象还挺奇怪的。可能GPU有一些nondeterministic的加速策略，不过我目前没有特别好的解释orz

好的好的，我也很奇怪
