### ISSUE TITLE
单事件&多事件

### ISSUE THREAD

**Issue by miraitowa9** [Spico197/DocEE#78]
想请教两个问题：
1.在ChFinAnn数据集上做单事件和多事件抽取时，是保持原始训练集和验证集不变，只将测试集换成单事件或多事件？还是将原始训练集和验证集也换成对应的单事件或多事件？
2. 为什么作者没有做Dueefin数据集在单事件和多事件上的对比实验结果啊？

**Comment by Spico197** [comment]
嗨您好，
1. 当前这版代码支持保证现有测试集不变，自动计算单事件和多事件结果，不需要额外处理
2. DuEE-Fin的线上评测代码不区分单事件和多事件，所以不好获得结果。不过可以看到dev上的单事件和多事件结果

**Comment by Spico197** [comment]
刚刚发现您这个问题是12月份提的，抱歉让您久等了。如果超过一天没有在GitHub上收到回复的话，可以直接发邮件给我

**Comment by miraitowa9** [comment]
好滴！非常感谢你的回复，祝您科研顺利！
