### ISSUE TITLE
Greedy-Dec模型如何运行？

### ISSUE THREAD

**Issue by miraitowa9** [Spico197/DocEE#79]
Greedy Dec是Doc2EDAG的一个简单基线。请问您的代码里面如何可以运行Greedy Dec吗？如果可以，方便告诉我怎么操作吗？非常感谢！

**Comment by Spico197** [comment]
嗨您好，感谢对本项目的关注。目前GreedyDec是运行Doc2EDAG时的“副产物”，需要运行 https://github.com/Spico197/DocEE/blob/main/scripts/run_doc2edag.sh 来获得（默认加了GreedyDec）。

https://github.com/Spico197/DocEE/blob/a32b6f8bf0b2fe28b9942b0b53eff461abf561ba/dee/tasks/dee_task.py#L130

**Comment by miraitowa9** [comment]
非常感谢您的回复，您的意思是 add_greedy_dec为True时运行的就是GreedyDec的结果，否则false就是Doc2EDAG的结果吗？

**Comment by Spico197** [comment]
运行 Doc2EDAG 的时候，如果 `add_greedy_dec` 为 `True`，则会顺便输出GreedyDec的结果，否则不运行GreedyDec。它目前是基于Doc2EDAG训练来获得的。

**Comment by miraitowa9** [comment]
如果 add_greedy_dec 为 True，运行 run_doc2edag.sh 后会同时输出Doc2EDAG和GreedyDec的两个结果嘛？

**Comment by Spico197** [comment]
嗯啊是的。您可以跑一轮看一下

**Comment by miraitowa9** [comment]
好的好的！我看到啦！谢谢！
