### ISSUE TITLE
结果中Average字段是否对应论文中的Macro的结果？

### ISSUE THREAD

**Issue by Rover912** [Spico197/DocEE#8]
![image](https://user-images.githubusercontent.com/42291852/148073700-cf4ca52e-fe4b-47c1-88e9-4d0fdd1b0c79.png)

Hi, 可以把图中Average的结果理解为对五种事件类型对应指标的平均吗，即论文中Macro的结果？

**Comment by Spico197** [comment]
您指的是最后在任务文件夹里生成的html文件吗？这部分是可以的。我只是把评价结果的部分放在了html文件里，结果和log中最后打印的结果相同。实验比较多的时候可以在`Exps/`文件夹里开启http服务，方便对比不同实验的最终结果。具体可以看下`run_dee_task.py`中对应的代码部分。
