### ISSUE TITLE
pretrained model weight

### ISSUE THREAD

**Issue by vvincenttttt** [Spico197/DocEE#82]
Hi,

nice repo.
Can you privide the PTPCG of DuEE-Fin model weight file?

thanks.

**Comment by Spico197** [comment]
Hi there, sorry for the late response. Thanks for your attention on our work~

Unfortunately, he checkpoint is missing. But training on DuEE-Fin is really fast, and you could reproduce the results on our data pre-processing and training scripts. If there are any problems about training, please let me know.

Thanks for your understanding.
