### ISSUE TITLE
大佬的天干地支随机种子选择法很好用，这篇事件抽取看的有点似懂非懂，甚至不知道怎么提问，大佬日后如果有线上分享希望能发一下

### ISSUE THREAD

**Issue by BEILOP** [Spico197/DocEE#9]

**Comment by Spico197** [comment]
哈哈，感谢您对这些项目的关注。后面如果有视频讲解的话会第一时间更新在本repo中。欢迎提问。

**Comment by BEILOP** [comment]
hhh，也thanks您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tong ***@***.***&gt;; 
发送时间: 2022年2月22日(星期二) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Spico197/DocEE] 大佬的天干地支随机种子选择法很好用，这篇事件抽取看的有点似懂非懂，甚至不知道怎么提问，大佬日后如果有线上分享希望能发一下 (Issue #9)





 
哈哈，感谢您对这些项目的关注。后面如果有视频讲解的话会第一时间更新在本repo中。欢迎提问。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
